"""
Hardware reference — pinouts, specifications, and hardware configuration for Botty.
Provides reference data for Raspberry Pi 5 and associated peripherals.
"""

RASPBERRY_PI_MODELS = {
    "pi5": {
        "name": "Raspberry Pi 5",
        "soc": "BCM2712",
        "cpu": "Quad Cortex-A76 @ 2.4GHz",
        "ram": "8GB LPDDR4X",
        "gpio_pins": 40,
        "i2c_buses": 2,
        "spi_buses": 2,
        "uart_ports": 2,
        "pwm_channels": 4,
        "usb_ports": 4,
        "camera_ports": 2,
        "display_ports": 2,
        "max_gpio_current": 16,
        "voltage": "5V 5A USB-C",
    },
}

GPIO_PIN_REFERENCE = {
    "physical_pins": {
        1: {"name": "3.3V", "type": "power"},
        2: {"name": "5V", "type": "power"},
        3: {"name": "GPIO2", "type": "i2c", "alt": "SDA1"},
        4: {"name": "5V", "type": "power"},
        5: {"name": "GPIO3", "type": "i2c", "alt": "SCL1"},
        6: {"name": "GND", "type": "ground"},
        7: {"name": "GPIO4", "type": "gpio"},
        8: {"name": "GPIO14", "type": "uart", "alt": "TXD0"},
        9: {"name": "GND", "type": "ground"},
        10: {"name": "GPIO15", "type": "uart", "alt": "RXD0"},
        11: {"name": "GPIO17", "type": "gpio"},
        12: {"name": "GPIO18", "type": "pwm"},
        13: {"name": "GPIO27", "type": "gpio"},
        14: {"name": "GND", "type": "ground"},
        15: {"name": "GPIO22", "type": "gpio"},
        16: {"name": "GPIO23", "type": "gpio"},
        17: {"name": "3.3V", "type": "power"},
        18: {"name": "GPIO24", "type": "gpio"},
        19: {"name": "GPIO10", "type": "spi", "alt": "MOSI"},
        20: {"name": "GND", "type": "ground"},
        21: {"name": "GPIO9", "type": "spi", "alt": "MISO"},
        22: {"name": "GPIO25", "type": "gpio"},
        23: {"name": "GPIO11", "type": "spi", "alt": "SCLK"},
        24: {"name": "GPIO8", "type": "spi", "alt": "CE0"},
        25: {"name": "GND", "type": "ground"},
        26: {"name": "GPIO7", "type": "spi", "alt": "CE1"},
        27: {"name": "GPIO0", "type": "i2c", "alt": "SDA0"},
        28: {"name": "GPIO1", "type": "i2c", "alt": "SCL0"},
        29: {"name": "GPIO5", "type": "gpio"},
        30: {"name": "GND", "type": "ground"},
        31: {"name": "GPIO6", "type": "gpio"},
        32: {"name": "GPIO12", "type": "pwm"},
        33: {"name": "GPIO13", "type": "pwm"},
        34: {"name": "GND", "type": "ground"},
        35: {"name": "GPIO19", "type": "pwm"},
        36: {"name": "GPIO16", "type": "gpio"},
        37: {"name": "GPIO26", "type": "gpio"},
        38: {"name": "GPIO20", "type": "gpio"},
        39: {"name": "GND", "type": "ground"},
        40: {"name": "GPIO21", "type": "gpio"},
    },
    "botty_wiring": {
        "ultrasonic_front_trigger": 5,
        "ultrasonic_front_echo": 6,
        "ultrasonic_left_trigger": 12,
        "ultrasonic_left_echo": 16,
        "ultrasonic_right_trigger": 20,
        "ultrasonic_right_echo": 21,
        "motor_left_forward": 17,
        "motor_left_backward": 18,
        "motor_left_enable": 13,
        "motor_right_forward": 22,
        "motor_right_backward": 23,
        "motor_right_enable": 24,
        "shovel_servo": 26,
        "oled_sda": 2,
        "oled_scl": 3,
        "camera_sda": 0,
        "camera_scl": 1,
    },
}

SENSOR_SPECIFICATIONS = {
    "HC-SR04": {
        "type": "Ultrasonic distance sensor",
        "voltage": "5V DC",
        "current": "15mA",
        "frequency": "40kHz",
        "range_min": "2cm",
        "range_max": "400cm",
        "resolution": "0.3cm",
        "accuracy": "±3mm",
        "measurement_angle": "15 degrees",
        "trigger_pulse": "10us",
        "echo_pulse": "100-25000us",
        "pin_count": 4,
    },
    "MPU6050": {
        "type": "6-axis IMU (accelerometer + gyroscope)",
        "voltage": "3.3-5V DC",
        "current": "3.6mA",
        "interface": "I2C",
        "i2c_address": "0x68 or 0x69",
        "accelerometer_range": "±2/±4/±8/±16g",
        "gyroscope_range": "±250/±500/±1000/±2000 °/s",
        "accelerometer_resolution": "16384 LSB/g (at ±2g)",
        "gyroscope_resolution": "131 LSB/°/s (at ±250°/s)",
        "temperature_sensor": True,
        "temperature_range": "-40 to +85 °C",
        "temperature_accuracy": "±1°C",
    },
    "DHT11": {
        "type": "Temperature and humidity sensor",
        "voltage": "3-5.5V DC",
        "current": "0.5-2.5mA",
        "temperature_range": "0-50°C",
        "temperature_accuracy": "±2°C",
        "humidity_range": "20-80%",
        "humidity_accuracy": "±5%",
        "sampling_rate": "1Hz (1 reading per second)",
        "pin_count": 4,
    },
    "DHT22": {
        "type": "Temperature and humidity sensor (high precision)",
        "voltage": "3.3-6V DC",
        "current": "1-1.5mA",
        "temperature_range": "-40 to 80°C",
        "temperature_accuracy": "±0.5°C",
        "humidity_range": "0-100%",
        "humidity_accuracy": "±2%",
        "sampling_rate": "0.5Hz (1 reading per 2 seconds)",
        "pin_count": 4,
    },
    "SSD1306": {
        "type": "OLED display controller",
        "voltage": "3.3-5V DC",
        "current": "20mA (all pixels on)",
        "interface": "I2C or SPI",
        "resolution": "128x64 pixels",
        "color": "Monochrome (white/blue/yellow)",
        "pixel_size": "0.96 inches diagonal",
        "viewing_angle": ">160 degrees",
        "contrast_control": True,
        "i2c_address": "0x3C",
    },
}

MOTOR_SPECIFICATIONS = {
    "N20_micro_gear_motor": {
        "type": "Micro gearmotor DC",
        "voltage": "3-6V DC",
        "no_load_rpm": 150,
        "rated_rpm": 100,
        "rated_torque": "0.5 kg·cm",
        "gear_ratio": "1:30",
        "shaft_diameter": "3mm",
        "weight": "10g",
        "encoder": "Optional magnetic encoder",
    },
    "MG996R_servo": {
        "type": "Standard servo motor",
        "voltage": "4.8-7.2V DC",
        "stall_torque": "10 kg·cm (at 6V)",
        "speed": "0.17s/60° (at 6V)",
        "rotation": "0-180 degrees",
        "weight": "55g",
        "pulse_width": "500-2500us",
        "pwm_frequency": "50Hz",
    },
}

POWER_BUDGET = {
    "raspberry_pi_5": {"typical": 5000, "max": 12000},
    "oled_display": {"typical": 20, "max": 25},
    "ultrasonic_sensor": {"typical": 15, "max": 20},
    "imu_mpu6050": {"typical": 3.6, "max": 5},
    "dht11_sensor": {"typical": 1, "max": 2.5},
    "motor_driver": {"typical": 100, "max": 500},
    "camera_usb": {"typical": 250, "max": 500},
    "total_estimated": {"typical": 5400, "max": 13000},
}

I2C_ADDRESS_MAP = {
    "0x3C": "SSD1306 OLED display",
    "0x3D": "SSD1306 OLED display (alt)",
    "0x68": "MPU6050 IMU (default)",
    "0x69": "MPU6050 IMU (alt)",
    "0x27": "PCF8574 I2C expander",
    "0x20": "MCP23017 I2C expander",
    "0x76": "BME280 temperature/humidity/pressure",
    "0x77": "BMP280 pressure sensor",
    "0x5C": "VL53L0X time-of-flight sensor",
    "0x29": "VL53L0X ToF (alt)",
    "0x40": "PCA9685 PWM controller",
    "0x48": "ADS1115 ADC",
}
