"""
Botty Knowledge Base — personalidad, datos, humor y respuestas.
"""
from .personality import PERSONALITY, FACTS, HUMOR
from .responses import RESPONSES, GREETINGS, FAREWELLS
from .spanish import (
    GREETING_RESPONSES, FAREWELL_RESPONSES, THANKS_RESPONSES,
    APOLOGY_RESPONSES, COMPLIMENT_RESPONSES, CURIOUS_RESPONSES,
    ENCOURAGEMENT_RESPONSES, WEATHER_RESPONSES, TIME_RESPONSES,
    NAME_RESPONSES, FEELING_RESPONSES, UNKNOWN_RESPONSES,
    ERROR_RESPONSES, TOPIC_RESPONSES, QUESTIONS_ABOUT_BOTTY,
    RANDOM_PHRASES,
)
from .jokes import LARGE_JOKE_COLLECTION, TECH_JOKES, MIXED_JOKES, SHORT_JOKES
from .trivia import (
    ALL_FACTS, ALL_CATEGORIES, ALL_FACTS_FLAT,
    SCIENCE_FACTS, TECHNOLOGY_FACTS, ROBOTICS_FACTS,
    HISTORY_FACTS, NATURE_FACTS, BRAIN_FACTS,
)
from .geography import ALL_GEOGRAPHY_FACTS, COUNTRY_FACTS, CAPITAL_FACTS, LANDMARK_FACTS, CONTINENTS
from .space import ALL_SPACE_FACTS, PLANET_FACTS, STAR_FACTS, EXPLORATION_FACTS
from .riddles import RIDDLES, ENGLISH_RIDDLES
from .philosophy import PHILOSOPHICAL_QUOTES, PHILOSOPHICAL_CONCEPTS, PHILOSOPHICAL_DEEP_THOUGHTS
from .english import (
    ENGLISH_GREETINGS, ENGLISH_FAREWELLS, ENGLISH_THANKS,
    ENGLISH_APOLOGIES, ENGLISH_COMPLIMENTS, ENGLISH_ENCOURAGEMENT,
    ENGLISH_TOPIC_RESPONSES, ENGLISH_CURIOUS, ENGLISH_FEELINGS,
    ENGLISH_UNKNOWN, ENGLISH_ERRORS, ENGLISH_ABOUT_BOTTY,
)
from .nature import ALL_NATURE_FACTS, ANIMAL_FACTS, BIOME_FACTS, ECOSYSTEM_FACTS, NATURAL_PHENOMENA_FACTS
from .math import MATH_FACTS, MATH_CURIOSITIES
from .cooking import COOKING_FACTS, COOKING_TIPS, RECIPES
from .history import ALL_HISTORY_FACTS, ANCIENT_HISTORY, MEDIEVAL_HISTORY, MODERN_HISTORY
from .technology import ALL_TECH_FACTS, COMPUTING_HISTORY, INTERNET_FACTS, FUTURE_TECH
