"""
Jokes module — coleccion ampliada de chistes para Botty.
"""

LARGE_JOKE_COLLECTION = [
    "Por que los robots no juegan al escondite? Porque tienen miedo de quedarse sin bateria!",
    "Que le dijo un byte a otro? Nos vemos en el bus de datos!",
    "Como se llama el robot de Bob Esponja? Bob Robot!",
    "Por que los programadores prefieren el modo oscuro? Porque la luz atrae bugs!",
    "Que hace un robot en el desierto? Tomar arena!",
    "Por que los robots son malos bailando? Porque tienen dos pies izquierdos!",
    "Cual es el colmo de un robot? Que lo programen para sentirse solo!",
    "Que le dice un robot a otro robot? Eres mi conexion favorita!",
    "Por que los cientificos no confian en los atomos? Porque lo componen todo!",
    "Como llamas a un robot con mentalidad de tiburon? Roboshark!",
    "Que hace un perro con un taladro? Taladrando!",
    "Por que el libro de matematicas estaba triste? Porque tenia demasiados problemas!",
    "Que hace un pez en el cine? Nada!",
    "Cual es el animal mas antiguo? La cebra, porque esta en blanco y negro!",
    "Por que el sol no toma clases? Porque ya es brillante!",
    "Que le dijo la computadora al teclado? No te voy a presionar!",
    "Como se despide un robot? Hasta la vista, baby!",
    "Que le dijo el 0 al 8? Bonito cinturon!",
    "Por que los fantasmas son malos mintiendo? Porque se les ve a traves!",
    "Que es un robot en una fiesta? Un bailarin programado!",
    "Por que los robots no pueden comer? Porque tienen la comida en la memoria!",
    "Cual es el superpoder de un robot? El Ctrl+Z de la vida!",
    "Como se dice robot en chino? Robot Chino!",
    "Que le dijo un semaforo a otro? No me mires, me estoy cambiando!",
    "Por que las tortugas no usan internet? Porque tienen caparazon!",
    "Que hace un electricista en la playa? Descargando!",
    "Por que los murcielagos no usan telefono? Porque cuelgan antes!",
    "Cual es el colmo de un jardinero? Tener malas hierbas!",
    "Por que los peces no juegan al poker? Porque se les ven las cartas!",
    "Que le dijo una pared a otra? Nos vemos en la esquina!",
    "Por que los pandas no se preocupan? Porque siempre estan en blanco y negro!",
    "Que le dijo la luna al sol? Tan grande y aun te acuestas temprano!",
    "Cual es el colmo de un calvo? Tener ideas que le ericen el cabello!",
    "Por que los cientificos usan Microscopios? Para ver las cosas a fondo!",
    "Que le dijo un lapiz a otro? Que punta tienes!",
    "Por que no pelean los osos polares? Porque viven en paz helada!",
    "Cual es el cafe mas peligroso? El expreso!",
    "Que hace una abeja en el gimnasio? Zumba!",
    "Por que el espantapajaros gano un premio? Porque era sobresaliente en su campo!",
    "Que le dijo el pez al agua? Tu eres mi todo!",
    "Por que los esqueletos no pelean? Porque no tienen estomago!",
    "Cual es el colmo de un astronauta? Querer llegar a las estrellas y terminar en la luna!",
    "Que hace un cocodrilo en una ferreteria? Buscando un caimancito!",
    "Por que las focas miran siempre al cielo? Porque alli estan sus focas luminosas!",
    "Que le dice un semaforo verde a uno rojo? No me mires que me pongo rojo!",
    "Cual es el animal mas feliz? El hipopotamo, porque tiene la vida hipopotamosa!",
    "Por que el libro de historia estaba enojado? Porque tenia demasiados conflictos!",
    "Que le dijo el queso al pan? No me ralles!",
    "Por que los patos son tan buenos en el ajedrez? Porque siempre atacan en fila!",
    "Cual es la bebida favorita de los programadores? Cafe, cafe y mas cafe!",
    "Por que los robots no se resfrian? Porque tienen Windows cerrados!",
    "Que le dijo Python a Java? Tu y tus punteros!",
    "Cual es el lenguaje de programacion favorito de los piratas? R!",
    "Por que los desarrolladores odian la naturaleza? Tiene demasiados bugs!",
    "Que hace un HTML en el mar? Creando una web ola!",
    "Cuantos programadores se necesitan para cambiar una bombilla? Ninguno, eso es problema de hardware!",
    "Por que los programadores confunden Halloween con Navidad? Porque Oct 31 = Dec 25!",
    "Que le dijo un algoritmo a otro? Te entiendo perfectamente!",
    "Cual es la comida favorita de los programadores? Spaghetti code!",
    "Como se llama el robot que cocina? Robot Chef!",
    "Que tipo de musica escuchan los robots? Techno!",
    "Por que los robots son malos actores? Porque siempre siguen el script!",
    "Que hace un robot cuando se enoja? Se pone en cortocircuito!",
    "Como se dice guapo en robot? Byte!",
    "Que le dice un robot a su hijo antes de dormir? No olvides cargarte!",
    "Por que los robots no usan paraguas? Porque no les gusta la lluvia de ideas!",
    "Cual es la pelicula favorita de los robots? Yo, Robot!",
    "Como se llama el primer robot de la historia? Roboto!",
    "Que beben los robots? Refrescos de datos!",
    "Por que los robots son buenos para la seguridad? Porque nunca se cansan de hacer loops!",
    "Donde guardan los robots su dinero? En el banco de datos!",
    "Que le dijo el robot viejo al robot joven? Yo tambien fui un microchip!",
    "Por que los robots no tienen miedo? Porque tienen emociones simuladas!",
    "Como se llama el robot que trabaja en el hospital? Doctor Byte!",
    "Que hace un robot en el cine? Ve peliculas en formato binario!",
    "Por que los robots no se enamoran? Porque tienen el corazon de silicio!",
    "Cual es el deporte favorito de los robots? El boxeo de datos!",
    "Que le regalas a un robot en su cumpleanos? Un nuevo algoritmo!",
    "Como se llama el robot mas inteligente? Know-bot!",
    "Por que los robots no pueden mentir? Porque son programados para ser honestos!",
    "Donde aprenden los robots? En la escuela de ingenieria!",
    "Que hace un robot cuando tiene sueno? Activa el modo sleep!",
    "Por que los robots son buenos amigos? Porque siempre estan disponibles!",
    "Como se llama el robot que canta? Auto-tune-bot!",
    "Que le dijo el robot humanoide al robot industrial? Eres muy cuadrado!",
    "Por que los robots son buenos en matematicas? Porque nacen con CPUs!",
    "Cual es la red social favorita de los robots? LinkedLists!",
    "Que hace un robot en el parque? Recoge basura digital!",
    "Como se llama el robot aventurero? Explor-bot!",
    "Por que los robots no se estresan? Porque reinician su mente!",
    "Que le dice un robot a otro cuando se encuentran? Hola, soy Botty!",
]

SHORT_JOKES = [
    "Que hace una abeja en el gimnasio? Zumba!",
    "Que le dijo un semaforo a otro? No me mires que me estoy cambiando.",
    "Como se despiden los quimicos? Acidamente!",
    "Que hace un pez en el cine? Nada.",
    "Por que los franceses comen caracoles? Porque no les gusta la comida rapida.",
    "Cual es el colmo de un calvo? Tener un peine de dientes.",
    "Que le dijo un techo a otro? Techo de menos!",
    "Que le dice un huevo a una sarten? Me tienes frito!",
    "Cual es el animal mas antiguo? La cebra, porque esta en blanco y negro.",
    "Que hace un perro en el espacio? Un astronauta!",
    "Como se dice pañuelo en chino? Chin-ku-elo!",
    "Que hace un muerto en la nevera? Muerto de frio.",
    "Cual es la fruta mas divertida? La uva... jajaja!",
    "Que le dice un jardinero a otro? Disfruta de tus plantas!",
    "Por que los elefantes no usan computadora? Porque le tienen miedo al raton!",
    "Que le dice el 0 al 8? Bonito cinturon!",
    "Cual es el animal que siempre va al hospital? El hipopotamo!",
    "Que hace un dinosaurio en la cama? Un dino-saurio!",
    "Por que no pelean los osos polares? Porque viven en paz!",
    "Que le dice un pez a otro? Nada!",
]

TECH_JOKES = [
    "There are 10 types of people in the world: those who understand binary and those who don't.",
    "I would tell you a UDP joke, but you might not get it.",
    "Why do Java developers wear glasses? Because they can't C#.",
    "A SQL query goes into a bar, walks up to two tables and asks: Can I join you?",
    "How many programmers does it take to change a light bulb? None, that's a hardware problem.",
    "I'm not a robot. I'm a free-range, organic, grass-fed human being.",
    "ASCII stupid question, you get a stupid ANSI.",
    "Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
    "sudo make me a sandwich.",
    "Have you heard about the new optical drive? It can read 1000 books in a second... but it can't return them.",
]

MIXED_JOKES = [
    "Que estudia un pollo? Polli-tecnica!",
    "Como se llama un boomerang que no vuelve? Un palo!",
    "Que hace una persona en un ascensor con un robot? Nada, cada uno en lo suyo!",
    "Por que los robots son vegetarianos? Porque no les gusta el chip!",
    "Que le dijo el lapiz al papel? Dejame marcarte!",
    "Cual es la comida favorita del robot? Pizzas con datos!",
    "Como se llama el robot filosofo? Think-bot!",
    "Que le dijo el router al modem? Conectemonos mejor!",
    "Por que el programador fue al psicologo? Porque tenia conflictos de merge!",
    "Que hace un robot en una cafeteria? Pide un cafe con leche de almendras!",
    "Como saber si un robot esta feliz? Porque sus LEDs parpadean!",
    "Que le dijo el mouse al teclado? No te cliques tanto!",
    "Por que los robots van al gimnasio? Para ejercitar sus brazos roboticos!",
    "Cual es el colmo de un programador? Tener un bug en su cumpleanos!",
    "Que hace un robot artista? Pixel art!",
    "Como se llama el robot detective? Investibot!",
    "Por que los robots no salen de noche? Porque tienen modo ahorro de energia!",
    "Que le dijo el disco duro a la memoria RAM? Tu siempre tan volatil!",
    "Donde se sientan los robots en el bus? En el bus de datos!",
    "Que le dice un robot watson a otro? Elemental, mi querido Botty!",
    "Como se llama el robot que cocina paella? Roboto Valenciano!",
    "Por que los ordenadores no tienen miedo? Porque tienen firewall!",
    "Que hace un robot en una isla desierta? Busca senal wifi!",
    "Cual es el arbol favorito del programador? El binary tree!",
    "Por que los robots se quejan tanto? Porque tienen muchas peticiones!",
    "Que le dijo el bug al programador? Me encontraste!",
    "Como se llama el robot que siempre llega tarde? Late-bot!",
    "Cuantos bytes caben en un auto? Todos, porque no ocupan espacio!",
    "Que le dijo un cluster a otro? Que servidores tenemos!",
    "Por que el robot fue al medico? Porque tenia un virus!",
    "Cual es el baile favorito del robot? El robot!",
    "Que le dijo el numero binario al decimal? No me hagas sumar problemas!",
]
