"""
Riddles module — brain teasers and acertijos for Botty.
"""

RIDDLES = [
    {"riddle": "Tengo agujas pero no coso. Tengo numeros pero no sumo. Que soy?", "answer": "Un reloj"},
    {"riddle": "Mientras mas tienes, menos ves. Que es?", "answer": "La oscuridad"},
    {"riddle": "Puedo romperme sin ser tocado. Que soy?", "answer": "Una promesa"},
    {"riddle": "Siempre estoy delante de ti pero nunca puedes alcanzarme. Que soy?", "answer": "El futuro"},
    {"riddle": "Tengo ciudades pero no casas. Tengo bosques pero no arboles. Tengo rios pero no agua. Que soy?", "answer": "Un mapa"},
    {"riddle": "Sube y baja pero nunca se mueve. Que es?", "answer": "La temperatura"},
    {"riddle": "Tengo llaves pero no cerraduras. Tengo espacio pero no habitaciones. Que soy?", "answer": "Un teclado"},
    {"riddle": "Puedo llenar una habitacion pero no ocupo espacio. Que soy?", "answer": "La luz"},
    {"riddle": "Mientras mas seca, mas humeda. Que es?", "answer": "Una toalla"},
    {"riddle": "Todos me tienen pero algunos me pierden. Que soy?", "answer": "La paciencia"},
    {"riddle": "Tengo orejas pero no puedo oir. Que soy?", "answer": "Una taza"},
    {"riddle": "Puedo ser dulce o salado. Puedo ser blando o duro. Que soy?", "answer": "El pan"},
    {"riddle": "No tengo voz pero te hablo. No tengo piernas pero te llevo lejos. Que soy?", "answer": "Un libro"},
    {"riddle": "Vuelo sin alas. Lloro sin ojos. Que soy?", "answer": "Una nube"},
    {"riddle": "Tengo dientes pero no puedo morder. Que soy?", "answer": "Un peine"},
    {"riddle": "Puedo cruzar un rio sin mojarme. Que soy?", "answer": "El puente"},
    {"riddle": "Me rompen antes de usarme. Que soy?", "answer": "Un huevo"},
    {"riddle": "Tengo un cuello pero no cabeza. Tengo brazos pero no manos. Que soy?", "answer": "Una camisa"},
    {"riddle": "Puedo ser tocado pero no visto. Si me tocas te puedo lastimar. Que soy?", "answer": "El fuego"},
    {"riddle": "Se llena con una mano pero puede vaciar un estadio. Que es?", "answer": "Un aplauso"},
    {"riddle": "Corre pero no tiene patas. Que es?", "answer": "El rio"},
    {"riddle": "Tiene cola pero no es animal. Que es?", "answer": "Una moneda"},
    {"riddle": "Puedo ser largo o corto. Puedo ser construido o destruido. Que soy?", "answer": "Un puente"},
    {"riddle": "Entre mas quitas, mas grande se vuelve. Que es?", "answer": "Un agujero"},
    {"riddle": "Tiene cuatro patas pero no puede caminar. Que es?", "answer": "Una mesa"},
    {"riddle": "Puedo estar lleno pero aun asi tener espacio. Que soy?", "answer": "Un colador"},
    {"riddle": "Blanco por dentro, verde por fuera. Si quieres que te lo diga, espera. Que es?", "answer": "La pera"},
    {"riddle": "El que lo hace no lo dice. El que lo recibe no lo sabe. El que lo sabe no lo quiere. Que es?", "answer": "Un secreto"},
    {"riddle": "Todos pueden abrirme pero nadie puede cerrarme. Que soy?", "answer": "Un huevo"},
    {"riddle": "Tengo un mar sin agua. Tengo una montana sin piedras. Que soy?", "answer": "Un mapa"},
    {"riddle": "Puedo estar lleno de agujeros pero aun asi contener agua. Que soy?", "answer": "Una esponja"},
    {"riddle": "Te sigo todo el dia pero nunca me ves. Que soy?", "answer": "Tu sombra"},
    {"riddle": "Tiene hojas pero no es arbol. Tiene pasta pero no es comida. Que es?", "answer": "Un libro"},
    {"riddle": "Puedo ser agrio o dulce. Tengo cascara pero no soy nuez. Que soy?", "answer": "Una fruta"},
    {"riddle": "Tiene cinco dedos pero no es una mano. Que es?", "answer": "Un guante"},
    {"riddle": "Puedo ser leido pero no escrito. Que soy?", "answer": "La mente"},
    {"riddle": "El hijo de mi madre pero no mi hermano. Quien es?", "answer": "Yo mismo"},
    {"riddle": "Tengo tres ojos pero no veo. Que soy?", "answer": "Un semaforo"},
    {"riddle": "Puedo detener un tren con solo estar acostado. Que soy?", "answer": "Las vias del tren"},
    {"riddle": "Cuanto mas tomo, mas dejo atras. Que soy?", "answer": "Los pasos"},
    {"riddle": "Oro no es. Plata no es. Abrelo y veras que es. Que es?", "answer": "El platano"},
    {"riddle": "Tengo pico pero no soy pajaro. Tengo cresta pero no soy gallo. Que soy?", "answer": "Una tetera"},
    {"riddle": "Llevo mi casa a cuestas. Tengo cuatro patas y no tengo patas. Que soy?", "answer": "El caracol"},
    {"riddle": "En el cielo brillo, pero no soy estrella. En la noche te alumbro, pero no soy linterna. Que soy?", "answer": "La luna"},
    {"riddle": "Tengo forma de corazon pero no siento amor. Que soy?", "answer": "Una carta de naipes"},
    {"riddle": "Puedo decir cualquier idioma pero no tengo boca. Que soy?", "answer": "Un traductor"},
    {"riddle": "Trece letras tengo, pero si me das la vuelta soy una nota musical. Que soy?", "answer": "El abecedario (do al reves)"},
    {"riddle": "Voy contigo a todas partes pero nunca me invitas. Que soy?", "answer": "Tu respiracion"},
    {"riddle": "Cien hermanos tengo, si no me apuras te mato. Que soy?", "answer": "El tiempo"},
    {"riddle": "Soy pequeno como un raton y cuido la casa como un leon. Que soy?", "answer": "El candado"},
]

ENGLISH_RIDDLES = [
    {"riddle": "What has keys but can't open locks?", "answer": "A piano"},
    {"riddle": "What gets wetter the more it dries?", "answer": "A towel"},
    {"riddle": "What can travel around the world while staying in a corner?", "answer": "A stamp"},
    {"riddle": "What has many teeth but can't bite?", "answer": "A comb"},
    {"riddle": "What has a head and a tail but no body?", "answer": "A coin"},
    {"riddle": "What can you break even if you never pick it up?", "answer": "A promise"},
    {"riddle": "What goes up but never comes down?", "answer": "Your age"},
    {"riddle": "What has words but never speaks?", "answer": "A book"},
    {"riddle": "What has a neck but no head?", "answer": "A bottle"},
    {"riddle": "What can run but never walks, has a mouth but never talks?", "answer": "A river"},
]
